[package]
name = "lambda_calc"
version = "0.1.0"
authors = ["Johan-Mi <johanmi@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
lalrpop = {version = "0.19", features = ["lexer"]}

[dependencies]
lalrpop-util = "0.19"
regex = "1"
derive_more = "0.99"

[profile.release]
lto = true
panic = "abort"
